# Generated by Django 5.0.4 on 2024-04-11 23:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('locale', models.CharField(default='-03:00', max_length=50, verbose_name='Fuso Horário')),
                ('lang', models.CharField(choices=[('pt', 'Portuguese'), ('es', 'Spanish'), ('en', 'English')], default='pt', max_length=2, verbose_name='Linguagem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('last_password_definition_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Última Redefinição de Senha')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email Verificado')),
                ('password', models.CharField(max_length=255, verbose_name='Senha')),
                ('primary_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('date_limit_to_sign', models.DateTimeField(verbose_name='Data Limite para Assinar')),
                ('signed', models.BooleanField(default=False, verbose_name='Assinado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_docs', to='core.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_created', to='core.user'),
        ),
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(related_name='managed_companies', to='core.user'),
        ),
    ]
