# Generated by Django 5.0.4 on 2024-04-12 00:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_company_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='docs',
            field=models.ManyToManyField(blank=True, related_name='associated_companies', to='core.doc'),
        ),
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='users_associated', to='core.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='users_associated', to='core.doc'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to='core.user'),
        ),
        migrations.AlterField(
            model_name='company',
            name='lang',
            field=models.CharField(choices=[('pt', 'Portuguese'), ('es', 'Spanish'), ('en', 'English')], default='pt', max_length=2),
        ),
        migrations.AlterField(
            model_name='company',
            name='locale',
            field=models.CharField(default='-03:00', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='managed_companies', to='core.user'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.company'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_documents', to='core.user'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='date_limit_to_sign',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='doc',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doc',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='doc',
            name='signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_password_definition_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='primary_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_user', to='core.company'),
        ),
    ]
