# Generated by Django 5.0.4 on 2024-04-12 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_docs_user_companies_user_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='date_limit_to_sign',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
