# Generated by Django 5.0.4 on 2024-04-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_doc_date_limit_to_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='date_limit_to_sign',
            field=models.DateTimeField(),
        ),
    ]
